# Run with:
# ansible-playbook SetupBackups.yml

---
- name: Setup Backups
  hosts: all
  tasks:

  - name: Create directory for backups
    file:
      path: "{{ item }}"
      state: directory
      owner: ajorians
      group: users
      mode: 0777
    loop:
      - /mnt/sync/backups
      - /mnt/backups/mailserver

  - name: Copy the copy script file with owner and permissions
    ansible.builtin.copy:
      src: BackupMailServer.sh
      dest: /mnt/backups
      owner: ajorians
      group: users
      mode: 0777

  - name: Ensure a job that backups the mailserver data"
    ansible.builtin.cron:
      name: "Backup mailserver data"
      minute: "0"
      hour: "3"
      job: "/mnt/backups/BackupMailServer.sh"
