# Run with:
# ansible-playbook -i inventory.ini ServerSetupSteps.yml --ask-vault-pass

---
- hosts: all

- import_playbook: Tasks/DebugSettings.yml
- import_playbook: Tasks/SetTimeZone.yml
- import_playbook: Tasks/CreateAJOriansUser.yml
- import_playbook: Tasks/ZypperUpdate.yml
- import_playbook: Tasks/InstallSudo.yml
- import_playbook: Tasks/InstallDocker.yml
- import_playbook: Tasks/InstallGit.yml
- import_playbook: Tasks/SetupGitCredentials.yml
- import_playbook: Tasks/InstallAnsible.yml
- import_playbook: Tasks/SetupMariaDB.yml
- import_playbook: Tasks/InstallMLocate.yml
- import_playbook: Tasks/InstallFtop.yml

- import_playbook: Tasks/InstallGCC.yml
- import_playbook: Tasks/InstallMake.yml
- import_playbook: Tasks/InstallOpenSSL.yml
- import_playbook: Tasks/InstallBZip2.yml
- import_playbook: Tasks/InstallPatch.yml
- import_playbook: Tasks/InstallLibEdit.yml
- import_playbook: Tasks/InstallUUID.yml
- import_playbook: Tasks/InstallJansson.yml
- import_playbook: Tasks/InstallXML2.yml
- import_playbook: Tasks/InstallSQLite3.yml

- import_playbook: Tasks/InstallScreen.yml
- import_playbook: Tasks/InstallRTorrent.yml
- import_playbook: Tasks/InstallUnrar.yml
- import_playbook: Tasks/InstallRSync.yml
- import_playbook: Tasks/InstallCertbot.yml
- import_playbook: Tasks/InstallApache2.yml
- import_playbook: Tasks/InstallPhp.yml
- import_playbook: Tasks/InstallKillAll.yml
- import_playbook: Tasks/InstallTCPDump.yml
- import_playbook: Tasks/InstallTelnet.yml
- import_playbook: Tasks/InstallNetTools.yml

- import_playbook: Docker/Mailserver/SetupMailServer.yml
- import_playbook: Tasks/InstallFail2Ban.yml
- import_playbook: Tasks/InstallMailClients.yml

- import_playbook: Docker/ResilioSync/SetupResilioSync.yml

- import_playbook: Tasks/InstallSnappyMail.yml

- import_playbook: Tasks/InstallVSFTP.yml

- import_playbook: Tasks/SetupMediaAssets.yml
- import_playbook: MediaWiki/InstallMediaWiki.yml
- import_playbook: MediaWiki/InstallSemanticRating.yml
- import_playbook: MediaWiki/SetMediaWikiLogo.yml
- import_playbook: MediaWiki/InstallTemplateStyles.yml

- import_playbook: Tasks/InstallBackdrop.yml

- import_playbook: Docker/Jellyfin/SetupJellyfin.yml
- import_playbook: Docker/NextCloud/SetupNextCloud.yml
- import_playbook: Docker/Flood/SetupFlood.yml

- import_playbook: Tasks/InstallBirthdays.yml 
- import_playbook: Tasks/InstallPhpMyAdmin.yml 

- import_playbook: Tasks/InstallInspircd.yml 
- import_playbook: Tasks/SetupIrcServer.yml
- import_playbook: Tasks/InstallXMPP.yml 

- import_playbook: Backups/SetupBackups.yml 
- import_playbook: Backups/InstallCronJobs.yml 

- import_playbook: Tasks/InstallAsterisk.yml 
- import_playbook: Tasks/InstallFreePBX.yml 
#- import_playbook: Tasks/SetupAsterisk.yml 

- import_playbook: SetupSSL.yml

