# Run with:
# ansible-playbook InstallOpenSSL.yml

---
- name: Install OpenSSL development
  hosts: all
  tasks:

  - name: Install OpenSSL development  package on OpenSUSE/SUSE Linux
    zypper:
      name: libopenssl-3-devel
      state: present

