# Run with:
# ansible-playbook InstallRSync.yml

---
- name: Install RSync
  hosts: all
  tasks:

  - name: Install rsync package on OpenSUSE/SUSE Linux
    zypper:
      name: rsync
      state: present

