# Run with:
# ansible-playbook -i inventory.ini SetupGitCredentials.yml

---
- name: Setup Git Credentials
  hosts: all
  tasks:
  - name: Set Git Name
    shell: git config --global user.name "A.J. Orians"

  - name: Set Git EMail
    shell: git config --global user.email "ajorians@gmail.com"
