# Run with:
# ansible-playbook SetupAsterisk.yml

---
- name: Setup Asterisk
  hosts: all
  tasks:

  - name: Math AGI Script
    ansible.builtin.get_url:
      url: http://mediaassets.orians.org/asterisk/math.agi
      dest: /var/lib/asterisk/agi-bin/math.agi

  - name: Change script permissions
    ansible.builtin.file:
      path: /var/lib/asterisk/agi-bin/math.agi
      owner: wwwrun
      group: www
      mode: '0755'

  - name: Download Good sound
    ansible.builtin.get_url:
      url: http://mediaassets.orians.org/asterisk/good.wav
      dest: /var/lib/asterisk/sounds/en/good.wav

  - name: Change good permissions
    ansible.builtin.file:
      path: /var/lib/asterisk/sounds/en/good.wav
      owner: wwwrun
      group: www
      mode: '0755'

  - name: Download Bad sound
    ansible.builtin.get_url:
      url: http://mediaassets.orians.org/asterisk/bad.wav
      dest: /var/lib/asterisk/sounds/en/bad.wav

  - name: Change bad permissions
    ansible.builtin.file:
      path: /var/lib/asterisk/sounds/en/bad.wav
      owner: wwwrun
      group: www
      mode: '0755'

  - name: Download Test Music
    ansible.builtin.get_url:
      url: http://mediaassets.orians.org/asterisk/test.mp3
      dest: /var/lib/asterisk/sounds/en/test.mp3

  - name: Change Test Music permissions
    ansible.builtin.file:
      path: /var/lib/asterisk/sounds/en/test.mp3
      owner: wwwrun
      group: www
      mode: '0755'

