version: "3"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - JELLYFIN_PublishedServerUrl=jellyfin.orians.org #optional
    volumes:
      - /opt/DockerSwarmData/jellyfin/config:/config
      - /opt/DockerSwarmData/jellyfin/tvshows:/data/tvshows
      - /opt/DockerSwarmData/jellyfin/movies:/data/movies
      - /mnt/download_files:/data/downloads
      - /mnt/allwrite/family:/data/family
      - /mnt/allwrite/favorites:/data/favorites
      - /mnt/allwrite/new:/data/new
      - /mnt/allwrite/brittany:/data/brittany
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
