# Run with:
# ansible-playbook InstallMediaWiki.yml

---
- name: Install MediaWiki
  hosts: all
  vars:
    mediawiki_version: "1.44.0"
  tasks:

  - name: check if mediawiki exists
    stat: 
      path: /srv/www/htdocs/mediawiki-{{mediawiki_version}}
    register: mediawiki_exists

  - name: Download MediaWiki
    ansible.builtin.get_url:
      url: https://releases.wikimedia.org/mediawiki/1.44/mediawiki-{{mediawiki_version}}.zip
      dest: /srv/www/htdocs/mediawiki-{{mediawiki_version}}.zip
    when: mediawiki_exists.stat.exists == false

  - name: Extract MediaWiki
    ansible.builtin.unarchive:
      src: /srv/www/htdocs/mediawiki-{{mediawiki_version}}.zip
      dest: /srv/www/htdocs
      remote_src: yes
    when: mediawiki_exists.stat.exists == false

  - name: Change permissions for MediaWiki
    ansible.builtin.file:
      path: /srv/www/htdocs/mediawiki-{{mediawiki_version}}
      owner: wwwrun
      group: www

  - name: check if rating extension exists
    stat:
      path: /srv/www/htdocs/mediawiki-{{mediawiki_version}}/extensions/SemanticRating
    register: semanticrating_exists

  - name: Create Database
    community.mysql.mysql_db:
      login_user: root
      name:
        - mediawiki
      state: present

  - name: Grant user access
    community.mysql.mysql_user:
      login_user: root
      state: present
      name: wikiuser
      host: 'localhost'
      password: wikipassword 
      priv:
        'mediawiki.*': 'ALL,GRANT'

  - name: Make Apache VHost file
    ansible.builtin.copy:
      dest: /etc/apache2/vhosts.d/mediawiki.conf
      force: false
      content: |
         <VirtualHost *:80>
           ServerAdmin webmaster@localhost
           DocumentRoot /srv/www/htdocs/mediawiki-{{mediawiki_version}}
           ServerName wiki.orians.org
           ServerAlias wiki mediawiki.orians.org mediawiki wiki.local newwiki.local
           <Directory /srv/www/htdocs/mediawiki-{{mediawiki_version}}>
              Options All
              AllowOverride All
           </Directory>
         </VirtualHost>
    notify:
    - Restart Apache2 service

  - name: Obtain SSL certificate
    shell: certbot --agree-tos --apache -m ajorians@gmail.com -n -d wiki.orians.org
    notify:
    - Restart Apache2 service

  handlers:
    - name: Restart Apache2 service
      ansible.builtin.systemd:
        state: restarted
        name: apache2
