# Run with
# ansible-playbook UpdateNextCloud.yml

---
- name: Update NextCloud Container
  hosts: all
  tasks:

  - name: Pull Latest Nextcloud
    community.docker.docker_compose_v2:
      project_src: /root/docker/nextcloud
      pull: always

  - name: Restart NextCloud
    community.docker.docker_compose_v2:
      project_src: /root/docker/nextcloud
      state: restarted


